Training.Mvc.OnlineStore.UI/Controllers/CategoryController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using Training.Mvc.OnlineStore.UI.Models;
using Training.Mvc.OnlineStore.UI.ViewModels;
using Training.Services.OnlineStore.Models;

namespace Training.Mvc.OnlineStore.UI.Controllers
{
    public class CategoryController : BaseController
    {
        public ActionResult ProductsByCategory(int id, int page, ProductSortBy sortBy = ProductSortBy.RateHighest)
        {
            int totalItems;
            var products = this.ProductService.GetAll(new ProductSearchFilter() { CategoryId = id, SortBy = sortBy }, out totalItems, page);

            var vm = new ListOfProductsViewModel()
            {
                List = new Pager<ProductViewModel>(Mapper.Map<IEnumerable<ProductViewModel>>(products), totalItems, page, urlFormat: string.Format("/category/{0}/{{0}}", id))
            };

            if (vm.List != null && vm.List.TotalItems > 0)
            {
                vm.ListTitle = CategoryService.GetById(id).Name;
            }

            return View("_ListOfProducts", vm);
        }
    }
}

Training.Mvc.OnlineStore.UI/Controllers/ProductController.cs
using System.Web.Mvc;
using AutoMapper;
using Training.Mvc.OnlineStore.UI.ViewModels;

namespace Training.Mvc.OnlineStore.UI.Controllers
{
    public class ProductController : BaseController
    {
        // GET: Product
        public ActionResult Details(int id)
        {
            var product = this.ProductService.GetById(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            return View(Mapper.Map<ProductViewModel>(product));
        }
    }
}

Training.Mvc.OnlineStore.UI/Areas/AdminPanel/Views/Shared/_Layout.cshtml
@model Training.Mvc.OnlineStore.UI.ViewModels.BaseViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - Online Store Back Office</title>

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/font-awesome.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/shop-homepage.css" rel="stylesheet">
    <link href="/css/sb-admin-2.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand glyphicon glyphicon-home" href="@Url.Action("Index", "Home", new { area = "" })"></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("LogOff", "Account")">Log off</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">Back Office Features</p>
                <div class="list-group">
                    <a href="@Url.Action("Index", "Dashboard")" class="list-group-item">Dashboard</a>
                    <a href="@Url.Action("Add", "Category")" class="list-group-item">Create category</a>
                    <a href="@Url.Action("Add", "Product")" class="list-group-item">Create product</a>
                </div>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>

<!-- Footer -->
    <div class="container">
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>&copy; @DateTime.Now.Year Moriyama - Online Store</p>
                </div>
            </div>
        </footer>
    </div>

    <!-- jQuery -->
    <script src="/Scripts/jquery-1.10.2.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/Scripts/bootstrap.min.js"></script>
</body>
</html>